language: python

install:
- cd mysite
- pip install -r requirements.txt
- pip install --upgrade awscli
before_script:
- python manage.py migrate
script:
- black --check .
- flake8 .
- coverage run --source=mysite,polls manage.py test
- coverage report
after_script:
- coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: us-east-1
  app: mysite
  env: django-env
  bucket_name: elasticbeanstalk-us-east-1-891377044770
  on:
    repo: devmcdonald/swe1-app
  skip_cleanup: 'true'
