language: python

install:
- cd mysite
- pip install -r requirements.txt
- pip install --upgrade awscli
before_script:
- python manage.py migrate
script:
- black --check .
- flake8 .
- coverage run --source=mysite,polls manage.py test
- coverage report
after_script:
- coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA47CRWJURISVIUQP5
  secret_access_key:
    secure: Ez966NfKEmO1Sf1/Qyrxh+nRvXEhBu1XoICrpnb1G/bIjPHje+DQPtFrSI7LlpA61Z3bFrlLb+QvO85RRLZfV17T+VkTuxZhWEVr+gkHY+Vy8pSrHBI6t7KB1eIH0nlhN7Bvq8QDr/G3911qh2sLqGyN5AcgVR45mDFBCR90rNGhUEvnscXQ1YRml74roJb30r6HgAJYAau6GBVj62H+1qDVsy8YHnLuTDD8OP3y0YMlzWHceRrPxG9qJW4cDY52KLu4vpEgyBB09o4JXwwZ0R0JbsWVgUGGJtD7YcuU5Wu0JqPGy8YHq+oCGPMqK0S06oQJC5xFIOO7iG5QmGcXvg1h2XmS63brUZff/sP6z89ZYcgTezzyPPMCLiLuvMK99snEAtkwmD2ShkhbC+X47Ths9DRB2g7f1C1aZWIisfSzWa1o/GSbZHAVtyui3/0sb/i8TybKN+aJsBlDo4YPjdQN/dybYf4b+JfYCNawgNq9UBHqbwrf9/8aBWC3SqJzTbxrTDcpR2A2MUSo9ztYY8VLlw+HAkpo64cGmDiZ4s95gs5kLBmRrtxSXHtaDxOin0851raFTuJVTWfBHlmGKg3alPaq50WH+biJzxQS+WHhizpxML/LTlO1Ssk5ijSnI5Yo9VWDzLIceRkXahGpgbipNku7CQts43XU5N3v+KU=
  region: us-east-1
  app: mysite
  env: django-env
  bucket_name: elasticbeanstalk-us-east-1-891377044770
  on:
    repo: devmcdonald/swe1-app
  skip_cleanup: 'true'
